### ISSUE TITLE
Push

### ISSUE THREAD

**Issue by FlorianDuquesne** [miage-lille/qsi-1-FlorianDuquesne#1]
Bonjour Monsieur,

Oumayma et moi avons travaillé ensemble sur les exercices sur même ordinateur. Une erreur est survenue lors de son push. En effet, cela s'est passé sur mon repo sans que l'on sache comment...

Ce n'est pas un vrai problème vu qu'on a travaillé ensemble mais je tenais à vous le signaler.

Merci d'avance.

Cordialement,
Florian Duquesne.

**Comment by oteku** [comment]
Bonjour Florian,
Même si les repos sont public en lecture, ils sont individuels en écriture

**Comment by FlorianDuquesne** [comment]
J'ai revert le commit d'Oumayma et j'ai pu repush le travail d'Oumayma sur son repo correctement.
Le problème provient du copier/coller du repo de base... (notamment le .git/)

Merci.
